esphome:
  name: genmon-rs232-bridge

substitutions:
  display_name: GenMon RS232 Bridge
  
esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  # Disable serial logging
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "GMSB"
    password: "complex1!"

captive_portal:
  
external_components:
  - source: github://oxan/esphome-stream-server

# Example configuration entry
dallas:
  - pin: 33

# Individual sensors
sensor:
  - platform: dallas
    index: 0
    name: "Board Temperature"

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: 2
  rx_pin: 15
  debug:
    direction: BOTH
    after:
      timeout: 100ms
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');   

stream_server:
   uart_id: uart_bus
   port: 6638
