version: '1'
services:
  genmon:
    build: .
    container_name: genmon
    image: genmon
    environment:
#      - TZ=America/New_York
      - TZ=America/Chicago
    ports:
      - 20022:22
      - 38443:443
      - 8000:8000
#docker-compose up -d
